### ISSUE TITLE
(Suggestion / Enhancement) Overheat damage 

### ISSUE THREAD

**Issue by ConstyCarlos** [Ash-LikeSnow/WeaponCore#21]
A method or a way to only do **DecayPerShot** when overheated (ie; heat bar is red)

or some new functions in **LoadingDef**:
**ShootOnOverheat** = [Boolean] | true or false; enables shooting on overheat/overheat damage, disables the other method of overheat where the weapon cannot fire
**OverheatDamage** = [int/float] | damage done to self block per shot

unsure if OverheatDamage can just take DecayPerShot from the ammo

This is essentially an alternate overheat mechanic where instead of the inability to shoot, it damages the weapon instead.

**Comment by BDCarrillo** [comment]
DecayPerShot of the ammo would apply all the time without a significant rework of logic.  Having OverheatDamage at the weapon def level makes more sense
