### ISSUE TITLE
Animation particles during prefire, reload, etc. loop forever when the host block is removed

### ISSUE THREAD

**Issue by InvalidArgument3** [Ash-LikeSnow/WeaponCore#22]
## Is this a multiplayer or singleplayer bug?

Both

## Describe the bug:

https://github.com/Ash-LikeSnow/WeaponCore/assets/51190031/9d4bda31-79b5-4f36-a532-6db5bb9f9bce

## Steps To Reproduce:

get any weapon with a prefire or reload particle, delete the block when firing

## Expected behavior:

the particle to disappear when the gun is deleted

**Comment by BDCarrillo** [comment]
Isolated to ProcessParticles().  MyDummy.Entity getter will result in NRE from block removal.  Existing property MyDummy.NullEntity used to early exit and shut down/clean anims
