### ISSUE TITLE
(Suggestion / Enhancement) User feedback for if weapon is below MinimumTargetingRange

### ISSUE THREAD

**Issue by InvalidArgument3** [Ash-LikeSnow/WeaponCore#29]
If you're within the minimum range of a weapon that uses it, for example a missile, trying to shoot gives no feedback on why it isn't getting a target. A ShowNotification or some other text on the HUD would be useful for users.

**Comment by BDCarrillo** [comment]
Educate your users.  It's not really feasible to ping message or hud text if your focused target is within min range of some weapons, but not others, or the weapon with the min range restriction has valid targets that aren't hud focused

**Comment by InvalidArgument3** [comment]
understandable
