### ISSUE TITLE
Cannot exit manual turret control

### ISSUE THREAD

**Issue by tuzet2** [Ash-LikeSnow/WeaponCore#39]
## Is this a multiplayer or singleplayer bug?
Singleplayer.

## Describe the bug:
After loading a world with Weapon Core, turrets will not allow you to exit their manual control.

## Steps To Reproduce:
1. Load a world, then exit and load it again. The bug does not appear if the world is played directly after its creation, neither during the first load of the game.
2. Sitting in a cockpit, take manual control of a gattling turret, then try to exit it with "F". (I have tested it and both gattling and custom turret has the bug)
3. You cannot, the bug persists through saves, if saved while controlling a turret, the world loaded from that save will also be bugged.

## Expected behavior:
You should be able to exit manual control of a turret.

### User Error Report (if Weapon-Specific) and log files
*WeaponCore lets you generate an error report for a specific weapon, while ingame, hold Ctrl+R and aim the red line at the Weapon that is erroring, and an error report will be generated in WeaponCores log cache: `Users\UserName\AppData\Roaming\SpaceEngineers\Storage\1918681825.sbm_WeaponCore`

Zip up that folder and link it here:
[3154371364.sbm_CoreSystems.zip](https://github.com/Ash-LikeSnow/WeaponCore/files/15048814/3154371364.sbm_CoreSystems.zip)

**Comment by BDCarrillo** [comment]
Not seeing this error if I'm in manual control of a gatling turret and save the game, then reload.  F exits properly.

**Comment by tuzet2** [comment]
It was caused by a faulty SpaceEngineers.cfg, belonging to the base game.
