### ISSUE TITLE
(Suggestion) Change weapon targeting logic for focused grids wrt nonfunctional blocks

### ISSUE THREAD

**Issue by klassekatze** [Ash-LikeSnow/WeaponCore#83]
**Is your feature request related to a problem? Please describe:**
Unintuitive/counterintuitive behavior of weapons targeting with regards to nonfunctional blocks. Weapons will shoot until destruction if the target block's grid is 'focused', but only shoot until nonfunctional if the target block's grid is not focused.

**Describe the solution or feature you'd like:**
Weapons should cease considering nonfunctional blocks valid targets, even if the target block's grid is focused.

**Additional context:**
When a ship fights another ship, they want to have as much information about the enemy as possible. In the absence of scripts or addons - and to some extent even with them - the best way to collect information on enemy ships is to cycle through them, focusing them in the UI. This is intuitive-- it's the logical course for a player.

However, more often than not I expect players want to mission kill an enemy, not literally vaporize them-- particularly when doing so costs ammunition.

Intuitively, be it by dead reckoning or sensors, many systems of an enemy ship should be (and are) able to be disabled without being completely destroyed. This reduces time-to-kill and by extension damage to your own vessel, and increases your profits in a salvage scenario, which is not uncommon both in multiplayer and even in singleplayer.

But counter-intuitively, that's not what happens when you focus on a threat. Instead, your ship decides in this specific situation to maintain focus on a given block until it is completely vaporized, even as non-disabled weapons and so on continue to hammer your vessel. This isn't something anyone would expect-- for their ship to choose to fight a focused threat, specifically, in a way that takes longer to kill threatening systems, resulting in you taking more damage, and recieve less salvage where that is relevant. On SD, at least, players unfamiliar with weaponcore are regularly confused by their ship "suddenly" deciding to attack disabled vessels in the event that they had not previously focused it. Many, even with years of experience, never understand what is happening until they are pro-actively warned by players "in the know." That's not good game design.

I vaguely recall that the intent of this behavior had something to do with preventing potential depowered stealth ships. Even if that's the case, though,checking for nonfunctional is distinct from checking for unpowered blocks. Welder shenanigans might still be applicable, but those would potentially apply with projectors even now, and niche cases don't justify confusing and frustrating players in the majority of actual combat scenarios.

In the unlikely event that there is a significant need for the current behavior, it should become a toggle option on the weapons themselves.

**Comment by klassekatze** [comment]
...Not to mention in a PVP scenario where one person doesn't know about this and the other does, the guy with this "secret knowledge" gets a potentially very significant advantage. Game-changing advantage, even.

**Comment by BDCarrillo** [comment]
Denied.  Proposal lacks any suggestion to determine how/when players can decide to pursue total destruction, which may be desirable in some situations.

**Comment by klassekatze** [comment]
> Denied. Proposal lacks any suggestion to determine how/when players can decide to pursue total destruction, which may be desirable in some situations.

Literally the last line of the proposal is a suggestion on that.

**Comment by klassekatze** [comment]
Furthermore, I don't understand your argument. Sure, there may be _some_ situations where this is desirable. But I went in depth to explain why I believe that isn't true of _most_ situations. It doesn't make sense to enable a niche behavior at the expense of frustrating and even upsetting players in 99% of situations. (The psychological impact of learning that you were literally screwed over by a mechanic you couldn't have reasonably predicted cannot be understated.)

**Comment by draconb** [comment]
Another "I want to totally destroy this" is just turn off subsystem targeting and let weapons go ham all over it.

But yes, having a toggle to allow "target non-functional" or "target only functional" would allow the user to decide how much overkill they want.

Its especially important on SDX as we have reactors that can tank 3-4 shots *after* they are no longer functional. Thats a lot of damage they are able to soak up when players select their target vs those that don't.

**Comment by klassekatze** [comment]
I want to emphasize that part of the issue isn't just that it's counter-intuitive, or that it's frustrating to work around, it's that intuition is all people have. Weaponcore does not have robust official documentation for players, and the many-years-out-of-date unofficial guides that come up in google don't mention this mechanic.

This means that if-and-when a player learns about this, if it has screwed them over in gameplay -- if they've lost a fight they'd have won if they defocused, which is not unlikely at all -- they feel like they didn't deserve it. It feels fundamentally unfair. And that's not the way any game should make a player feel.
